namespace: extreme
name: slxos
version: 0.1.0
readme: README.md
authors:
    - Ujwal Komarla
description: An Ansible collection for managing Extreme Networks devices running SLXOS.
license: GPL-3.0-or-later
license_file: COPYING
dependencies:
  "ansible.netcommon": "*"
repository: git@github.com:extremenetworks/ansible_collections.extreme.slxos.git
documentation: https://github.com/extremenetworks/ansible_collections.extreme.slxos/tree/master/docs
homepage: https://github.com/extremenetworks/ansible_collections.extreme.slxos
issues: https://github.com/extremenetworks/ansible_collections.extreme.slxos/issues
tags:
    - networking
    - slxos
    - extreme
    - switching
    - collection
    - datacenter
